version: '3.7'

networks:
  tsunagu-net:
    driver: bridge

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - tsunagu-net
    restart: on-failure
    container_name: tsunagu-postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DATABASE: ${POSRGRES_DATABASE:-tsunagu_db}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
